// ─────────────────────────────────────────────────────────────────────────────
// GameplayLogger — records game events for playtesting analysis.
//
// Usage:
//   import logger from './GameplayLogger.js';
//   logger.logRoundStart(roundNum, actNum, threshold, hand, field);
//   logger.logAction('play', { cardId: 'january_crane', fieldTarget: 'january_plain' });
//   ...
//   const transcript = logger.getTranscript();
//
// The transcript is plain text, structured with clear delimiters for each
// round and shop visit. Designed to be copy/pasted into a conversation for
// analysis.
// ─────────────────────────────────────────────────────────────────────────────

class GameplayLogger {
  constructor() {
    this._entries = [];
    this._enabled = true;
    this._currentRound = 0;
    this._currentAct = 0;
    this._runStartTime = Date.now();
  }

  enable()  { this._enabled = true; }
  disable() { this._enabled = false; }
  get enabled() { return this._enabled; }

  _log(entry) {
    if (!this._enabled) return;
    this._entries.push(entry);
    console.log(entry);
  }

  _separator(label) {
    this._log(`\n${'═'.repeat(60)}`);
    this._log(label);
    this._log('═'.repeat(60));
  }

  // ── Run lifecycle ──────────────────────────────────────────────────────

  logRunStart() {
    this._entries = [];
    this._runStartTime = Date.now();
    this._separator('RUN START');
    this._log(`Timestamp: ${new Date().toISOString()}`);
  }

  logRunEnd(reason, finalRound) {
    this._separator(`RUN END — ${reason}`);
    this._log(`Final round reached: ${finalRound}`);
    this._log(`Run duration: ${Math.round((Date.now() - this._runStartTime) / 1000)}s`);
  }

  // ── Round lifecycle ────────────────────────────────────────────────────

  /**
   * @param {number} roundNum
   * @param {number} actNum
   * @param {number} threshold
   * @param {object[]} hand — array of card objects dealt to hand
   * @param {object[]} field — array of card objects dealt to field
   * @param {number} earthKiGain — ki generated by Earth enhancements this round
   * @param {number} kiBalance — ki balance at round start
   * @param {number} deckSize — total cards in deck
   */
  logRoundStart(roundNum, actNum, threshold, hand, field, earthKiGain, kiBalance, deckSize) {
    this._currentRound = roundNum;
    this._currentAct = actNum;
    this._separator(`ROUND ${roundNum} (Act ${actNum}) — Threshold: ${threshold}`);
    this._log(`Ki: ${kiBalance} | Deck size: ${deckSize}`);
    if (earthKiGain > 0) this._log(`Earth ki interest: +${earthKiGain}`);
    this._log(`Hand: ${hand.map(c => this._cardLabel(c)).join(', ')}`);
    this._log(`Field: ${field.map(c => this._cardLabel(c)).join(', ')}`);
  }

  /**
   * Log the spirit loadout at the start of each round.
   * @param {object[]} spirits — array of spirit objects
   */
  logHexagramAssignment(hexagram) {
    if (!hexagram) { this._log('Hexagram: (none)'); return; }
    this._log(`Hexagram: ${hexagram.englishName} (${hexagram.chineseCharacter} ${hexagram.chineseName}) [${hexagram.id}]`);
    this._log(`  ${hexagram.description}`);
  }

  logSpiritLoadout(spirits, negatives = [], legendaries = []) {
    if (spirits.length === 0 && negatives.length === 0 && legendaries.length === 0) {
      this._log('Spirits: (none)');
      return;
    }
    const fmt = (s) => {
      let d = s.name;
      if (s.stackCount > 1) d += ` \xD7${s.stackCount}`;
      if (s.isNegative && s.powerLevel) d += ` (neg p${s.powerLevel})`;
      if (s.elements && s.elements.length > 0) d += ` [el:${s.elements.length}]`;
      else if (s.state) {
        const bits = [];
        for (const [k, v] of Object.entries(s.state)) {
          if (v === null || v === undefined) continue;
          if (Array.isArray(v)) bits.push(`${k}:${v.length}`);
          else if (typeof v !== 'object') bits.push(`${k}:${v}`);
        }
        if (bits.length > 0) d += ` [${bits.join(', ')}]`;
      }
      return d;
    };
    const parts = [];
    if (spirits.length > 0)     parts.push(`Regular: ${spirits.map(fmt).join(' | ')}`);
    if (negatives.length > 0)   parts.push(`Negative: ${negatives.map(fmt).join(' | ')}`);
    if (legendaries.length > 0) parts.push(`Legendary: ${legendaries.map(fmt).join(' | ')}`);
    this._log(`Spirits: ${parts.join(' || ')}`);
  }

  // ── Player actions ─────────────────────────────────────────────────────

  /**
   * @param {string} type — 'play', 'discard'
   * @param {object} details
   */
  logAction(type, details) {
    if (type === 'play') {
      const cards = details.cardIds || [details.cardId];
      this._log(`  PLAY: ${cards.map(id => id).join(', ')} → field month ${details.targetMonth ?? '?'}`);
    } else if (type === 'discard') {
      this._log(`  DISCARD: ${details.cardId}`);
    }
  }

  /**
   * @param {object} deckCard — the card flipped from the deck
   * @param {string} result — 'capture', 'strand', 'silk_capture', 'field_place', 'field_discard'
   * @param {object[]} capturedCards — cards captured as a result (if any)
   */
  logDeckFlip(deckCard, result, capturedCards) {
    let msg = `  FLIP: ${this._cardLabel(deckCard)} → ${result}`;
    if (capturedCards && capturedCards.length > 0) {
      msg += ` [captured: ${capturedCards.map(c => this._cardLabel(c)).join(', ')}]`;
    }
    this._log(msg);
  }

  /**
   * @param {object[]} cards — cards captured
   * @param {string} reason — 'match', 'auto_complete', 'four_card'
   */
  logCapture(cards, reason) {
    this._log(`  CAPTURE (${reason}): ${cards.map(c => this._cardLabel(c)).join(', ')}`);
  }

  // ── Yaku and style ─────────────────────────────────────────────────────

  /**
   * @param {object[]} yakuList — array of { name, bonus, count, threshold }
   * @param {object[]} newYaku — newly completed yaku this turn
   */
  logYakuState(yakuList, newYaku) {
    if (yakuList.length === 0) return;
    const yakuStr = yakuList.map(y => `${y.name} (${y.count}/${y.threshold})`).join(', ');
    this._log(`  YAKU: ${yakuStr}`);
    if (newYaku && newYaku.length > 0) {
      this._log(`  ► NEW YAKU: ${newYaku.map(y => y.name).join(', ')} → Bank/Push triggered`);
    }
  }

  /**
   * @param {object[]} combos — array of { name, bonus }
   */
  logStyleCombos(combos) {
    if (combos.length === 0) return;
    const str = combos.map(c => `${c.name} +${c.bonus.toFixed(1)}`).join(', ');
    this._log(`  STYLE: ${str}`);
  }

  // ── Bank/Push ──────────────────────────────────────────────────────────

  logBankPushDecision(decision, pushCount) {
    this._log(`  DECISION: ${decision.toUpperCase()} (push #${pushCount})`);
  }

  // ── Consumable usage ───────────────────────────────────────────────────

  /**
   * @param {string} consumableName
   * @param {string} action — description of what happened
   */
  logConsumableUse(consumableName, action) {
    this._log(`  CONSUMABLE: ${consumableName} — ${action}`);
  }

  // ── Round end ──────────────────────────────────────────────────────────

  /**
   * @param {object} scoring — full scoring breakdown
   * @param {number} threshold
   * @param {boolean} cleared
   * @param {object[]} capturedCards — full capture pile
   * @param {object[]} triggeredCombos — style combos triggered this round
   * @param {string[]} enhancementEvents — any enhancement post-round events (breaks, etc.)
   */
  logRoundEnd(scoring, threshold, cleared, capturedCards, triggeredCombos, enhancementEvents) {
    this._log('');
    this._log(`  ── Round ${this._currentRound} Scoring ──`);
    this._log(`  Captured: ${capturedCards.length} cards`);

    // Card type breakdown
    const types = { bright: 0, animal: 0, ribbon: 0, plain: 0, fire: 0 };
    for (const c of capturedCards) {
      if (c.enhancement?.element === 'fire') types.fire++;
      else types[c.type] = (types[c.type] ?? 0) + 1;
    }
    this._log(`  Types: ${types.bright}B ${types.animal}A ${types.ribbon}R ${types.plain}P` +
      (types.fire > 0 ? ` ${types.fire}F(wildcard)` : ''));

    this._log(`  Base points: ${scoring.basePoints ?? '?'}`);
    this._log(`  Flow: ×${scoring.flow?.toFixed(2) ?? '?'}`);
    this._log(`  FINAL SCORE: ${scoring.finalScore}`);
    this._log(`  Threshold: ${threshold} — ${cleared ? '✓ CLEARED' : '✗ FAILED'}`);

    // Style summary
    if (triggeredCombos && triggeredCombos.length > 0) {
      this._log(`  Style combos: ${triggeredCombos.map(c => c.name).join(', ')}`);
    }

    // Enhancement events
    if (enhancementEvents && enhancementEvents.length > 0) {
      for (const evt of enhancementEvents) {
        this._log(`  Enhancement: ${evt}`);
      }
    }
  }

  // ── Shop ───────────────────────────────────────────────────────────────

  logShopEnter(kiBalance, isGrove) {
    this._log('');
    this._log(`  ── ${isGrove ? 'Sacred Grove' : 'Wayside Shrine'} (Ki: ${kiBalance}) ──`);
  }

  logShopPurchase(category, itemName, cost, details) {
    let msg = `  BUY: ${itemName} (${cost} ki)`;
    if (details) msg += ` — ${details}`;
    this._log(msg);
  }

  logShopFusion(spiritA, spiritB, result) {
    this._log(`  FUSE: ${spiritA} + ${spiritB} → ${result}`);
  }

  logShopExit(kiBalance) {
    this._log(`  Exit shop (Ki: ${kiBalance})`);
  }

  // ── Run summary ────────────────────────────────────────────────────────

  /**
   * Generate a summary block at the end of the run.
   * @param {object} runState — snapshot of RunManager state
   */
  logRunSummary(runState) {
    this._separator('RUN SUMMARY');
    this._log(`Rounds completed: ${runState.round}`);
    this._log(`Final ki: ${runState.ki}`);

    // Spirits
    if (runState.spirits && runState.spirits.length > 0) {
      this._log(`Spirits: ${runState.spirits.map(s => {
        let detail = s.name;
        if (s.state?.plainsCaptured !== undefined) detail += ` [plains: ${s.state.plainsCaptured}]`;
        if (s.state?.seenAnimals) detail += ` [animals: ${s.state.seenAnimals.length}/9]`;
        return detail;
      }).join(', ')}`);
    }

    // Deck state
    if (runState.deckSize !== undefined) {
      this._log(`Deck size: ${runState.deckSize}/48`);
    }

    // Enhanced cards
    if (runState.enhancedCards && runState.enhancedCards.length > 0) {
      this._log(`Enhanced cards:`);
      for (const c of runState.enhancedCards) {
        this._log(`  ${c.id}: ${c.enhancement.tier} ${c.enhancement.element}` +
          (c.enhancement.depLevel !== undefined ? ` (dep: ${c.enhancement.depLevel})` : ''));
      }
    }

    // Promoted cards
    if (runState.promotedCards && runState.promotedCards.length > 0) {
      this._log(`Promoted cards:`);
      for (const c of runState.promotedCards) {
        this._log(`  ${c.id} (${c.type})`);
      }
    }
  }

  // ── Spirit lifecycle ──────────────────────────────────────────────────

  logSpiritSold(spiritName, kiReturned, slotIndex) {
    this._log(`  [SPIRIT SOLD] ${spiritName} from slot ${slotIndex} (+${kiReturned} ki)`);
  }

  logSpiritStacked(spiritName, newStackCount) {
    this._log(`  [SPIRIT STACKED] ${spiritName} → stack ${newStackCount}`);
  }

  logSpiritTranscended(spiritName) {
    this._log(`  [SPIRIT TRANSCENDED] ${spiritName} → negative copy`);
  }

  // ── Blessings ───────────────────────────────────────────────────────────

  logBlessingObtained(blessingId, blessingName, tier) {
    this._log(`  [BLESSING] ${blessingName} (Tier ${tier}, ${blessingId})`);
  }

  // ── Consumable lifecycle ────────────────────────────────────────────────

  logConsumableSold(consumableName, kiReturned) {
    this._log(`  [CONSUMABLE SOLD] ${consumableName} (+${kiReturned} ki)`);
  }

  logNegativeConsumableObtained(consumableName, source) {
    this._log(`  [NEG CONSUMABLE] ${consumableName} (${source})`);
  }

  // ── Ki transactions ─────────────────────────────────────────────────────

  logKiChange(delta, reason, newBalance) {
    const sign = delta >= 0 ? '+' : '';
    this._log(`  [KI] ${sign}${delta} (${reason}) → ${newBalance}`);
  }

  // ── Flow changes ────────────────────────────────────────────────────────

  logFlowChange(oldValue, newValue, reason, operation = 'multiplicative') {
    let suffix;
    if (operation === 'additive') {
      const delta = (newValue - oldValue).toFixed(3);
      const sign = parseFloat(delta) >= 0 ? '+' : '';
      suffix = `${sign}${delta}`;
    } else {
      const multiplier = oldValue !== 0 ? (newValue / oldValue).toFixed(3) : 'n/a';
      suffix = `\xD7${multiplier}`;
    }
    this._log(`  [FLOW] ${oldValue.toFixed(3)} → ${newValue.toFixed(3)} (${suffix}, ${reason})`);
  }

  // ── Shop offerings ──────────────────────────────────────────────────────

  logShopOfferings(sections) {
    this._log('  Shop offerings:');
    for (const section of sections) {
      if (!section.items || section.items.length === 0) continue;
      this._log(`    ${section.name}: ${section.items.map(i => `${i.name ?? i.id}(${i.cost ?? '?'}ki)`).join(', ')}`);
    }
  }

  // ── Card lifecycle ──────────────────────────────────────────────────────

  logCardEnhanced(cardName, element, tier) {
    this._log(`  [CARD ENHANCED] ${cardName} → ${tier} ${element}`);
  }

  logCardStamped(cardName, stampId) {
    this._log(`  [CARD STAMPED] ${cardName} → ${stampId}`);
  }

  logCardEditionApplied(cardName, edition) {
    this._log(`  [CARD EDITION] ${cardName} → ${edition}`);
  }

  logCardDestroyed(cardName, reason) {
    this._log(`  [CARD DESTROYED] ${cardName} (${reason})`);
  }

  logCardAdded(cardName, source) {
    this._log(`  [CARD ADDED] ${cardName} (${source})`);
  }

  logCardTranscended(sourceName, targetName) {
    this._log(`  [CARD TRANSCENDED] ${sourceName} → copy of ${targetName}`);
  }

  // ── Yaku thresholds ─────────────────────────────────────────────────────

  logYakuThresholds(thresholds, deckComp) {
    this._log(`  [THRESHOLDS] ★(${thresholds.hikari}) ♦(${thresholds.tane}) ║(${thresholds.tanzaku}) □(${thresholds.kasu}) — deck: ${deckComp.bright}B ${deckComp.animal}A ${deckComp.ribbon}R ${deckComp.plain}P (${deckComp.total})`);
  }

  logYakuAchieved(yakuName, count, threshold) {
    this._log(`  [YAKU ACHIEVED] ${yakuName}: ${count} captured (threshold ${threshold})`);
  }

  // ── Granular capture scoring ──────────────────────────────────────────

  /**
   * Log a capture scoring event with full per-card and capture-level breakdown.
   */
  logCaptureScoring(data) {
    this._log('');
    this._log('\u2500'.repeat(54));
    this._log(`CAPTURE #${data.captureNumber} \u2014 Turn ${data.turn}, Phase: ${data.phase}`);
    this._log('\u2500'.repeat(54));

    this._log(`Cards captured (${data.cardBreakdowns.length}):`);
    for (const cb of data.cardBreakdowns) {
      this._log(`  \u2022 ${cb.cardName} (${cb.meta})`);
      this._log(`      base points: ${cb.basePoints}`);
      for (const c of cb.contributions) {
        this._log(`      + ${c.source}: ${this._fmtContrib(c)}`);
      }
      this._log(`      card contribution: ${cb.totalCardPts} pts`);
    }

    this._log('');
    this._log('Capture-level:');
    if (data.captureLevel.heldEffects.length === 0) {
      this._log('  Held-in-hand: (none)');
    } else {
      this._log('  Held-in-hand:');
      for (const h of data.captureLevel.heldEffects) {
        this._log(`    \u2022 ${h.source}: ${this._fmtContrib(h)}`);
      }
    }
    if (data.captureLevel.engineSpirits.length === 0) {
      this._log('  Engine spirits: (none)');
    } else {
      this._log('  Engine spirits:');
      for (const e of data.captureLevel.engineSpirits) {
        this._log(`    \u2022 ${e.source}: ${this._fmtContrib(e)}`);
      }
    }

    this._log('');
    this._log('Scoring math:');
    this._log(`  points: ${data.totalPoints}`);
    this._log(`  mult: ${data.totalMult.toFixed(2)}`);
    this._log(`  flow: ${data.flow.toFixed(2)}`);
    this._log(`  custom formula: ${data.customFormula || '(none \u2014 standard pts \u00D7 mult \u00D7 flow)'}`);
    this._log(`  FINAL: ${data.captureScore.toLocaleString()}`);
    this._log('');
    this._log(`Running round total: ${data.runningRoundTotal.toLocaleString()}`);
    this._log('\u2500'.repeat(54));
  }

  /**
   * Log a stamp retrigger scoring event.
   */
  logRetriggerScoring(data) {
    this._log('');
    this._log(`\u2500\u2500 Retrigger (${data.stampType} on ${data.cardName}) \u2500\u2500`);
    this._log(`  base points: ${data.basePoints}`);
    for (const c of data.contributions) {
      this._log(`  + ${c.source}: ${this._fmtContrib(c)}`);
    }
    this._log(`  retrigger pts: ${data.retriggerPts}, mult: ${data.retriggerMult.toFixed(2)}`);
    this._log(`  score: ${data.retriggerScore.toLocaleString()}`);
    this._log(`  Running round total: ${data.runningRoundTotal.toLocaleString()}`);
  }

  _fmtContrib(c) {
    const parts = [];
    if (c.addPoints)    parts.push(`+${c.addPoints} pts`);
    if (c.addMult)      parts.push(`+${c.addMult} mult`);
    if (c.multiplyMult && c.multiplyMult !== 1) parts.push(`\u00D7${c.multiplyMult} mult`);
    return parts.join(', ') || '(no effect)';
  }

  // ── Helpers ─────────────────────────────────────────────────────────────

  _cardLabel(card) {
    let label = card.name ?? card.id;
    if (card.enhancement) {
      const enh = card.enhancement;
      const names = {
        water: { base: 'Snow', upgraded: 'Ice' },
        wood:  { base: 'Leaf', upgraded: 'Silk' },
        fire:  { base: 'Ember', upgraded: 'Charcoal' },
        earth: { base: 'Clay', upgraded: 'Pottery' },
        metal: { base: 'Iron', upgraded: 'Meteorite' },
      };
      const enhName = names[enh.element]?.[enh.tier] ?? enh.element;
      label += `[${enhName}`;
      if (enh.element === 'water') {
        const SNOW = [2.0, 1.5, 1.0, 0.75, 0.5, 0.25];
        const ICE  = [4.0, 3.0, 2.0, 1.5, 1.0, 0.75, 0.5, 0.25];
        const arr = enh.tier === 'upgraded' ? ICE : SNOW;
        const lvl = Math.min(enh.depLevel ?? 0, arr.length - 1);
        label += ` ×${arr[lvl]}`;
      }
      label += ']';
    }
    if (card.promotionProgress) {
      label += `{promo:${card.promotionProgress}}`;
    }
    return label;
  }

  // ── Output ──────────────────────────────────────────────────────────────

  /**
   * Get the full transcript as a string.
   */
  getTranscript() {
    return this._entries.join('\n');
  }

  /**
   * Copy transcript to clipboard (browser only).
   */
  async copyToClipboard() {
    const text = this.getTranscript();
    try {
      await navigator.clipboard.writeText(text);
      console.log('[GameplayLogger] Transcript copied to clipboard.');
      return true;
    } catch (e) {
      console.warn('[GameplayLogger] Clipboard copy failed:', e);
      return false;
    }
  }

  /**
   * Log transcript to browser console.
   */
  printToConsole() {
    console.log(this.getTranscript());
  }
}

const logger = new GameplayLogger();
export default logger;
