// ─────────────────────────────────────────────────────────────────────────────
// GameplayLogger — records game events for playtesting analysis.
//
// Usage:
//   import logger from './GameplayLogger.js';
//   logger.logRoundStart(roundNum, actNum, threshold, hand, field);
//   logger.logAction('play', { cardId: 'january_crane', fieldTarget: 'january_plain' });
//   ...
//   const transcript = logger.getTranscript();
//
// The transcript is plain text, structured with clear delimiters for each
// round and shop visit. Designed to be copy/pasted into a conversation for
// analysis.
// ─────────────────────────────────────────────────────────────────────────────

class GameplayLogger {
  constructor() {
    this._entries = [];
    this._enabled = true;
    this._currentRound = 0;
    this._currentAct = 0;
    this._runStartTime = Date.now();
  }

  enable()  { this._enabled = true; }
  disable() { this._enabled = false; }
  get enabled() { return this._enabled; }

  _log(entry) {
    if (!this._enabled) return;
    this._entries.push(entry);
    console.log(entry);
  }

  _separator(label) {
    this._log(`\n${'═'.repeat(60)}`);
    this._log(label);
    this._log('═'.repeat(60));
  }

  // ── Run lifecycle ──────────────────────────────────────────────────────

  logRunStart() {
    this._entries = [];
    this._runStartTime = Date.now();
    this._separator('RUN START');
    this._log(`Timestamp: ${new Date().toISOString()}`);
  }

  logRunEnd(reason, finalRound) {
    this._separator(`RUN END — ${reason}`);
    this._log(`Final round reached: ${finalRound}`);
    this._log(`Run duration: ${Math.round((Date.now() - this._runStartTime) / 1000)}s`);
  }

  // ── Round lifecycle ────────────────────────────────────────────────────

  /**
   * @param {number} roundNum
   * @param {number} actNum
   * @param {number} threshold
   * @param {object[]} hand — array of card objects dealt to hand
   * @param {object[]} field — array of card objects dealt to field
   * @param {number} earthKiGain — ki generated by Earth enhancements this round
   * @param {number} kiBalance — ki balance at round start
   * @param {number} deckSize — total cards in deck
   */
  logRoundStart(roundNum, actNum, threshold, hand, field, earthKiGain, kiBalance, deckSize) {
    this._currentRound = roundNum;
    this._currentAct = actNum;
    this._separator(`ROUND ${roundNum} (Act ${actNum}) — Threshold: ${threshold}`);
    this._log(`Ki: ${kiBalance} | Deck size: ${deckSize}`);
    if (earthKiGain > 0) this._log(`Earth ki interest: +${earthKiGain}`);
    this._log(`Hand: ${hand.map(c => this._cardLabel(c)).join(', ')}`);
    this._log(`Field: ${field.map(c => this._cardLabel(c)).join(', ')}`);
  }

  /**
   * Log the spirit loadout at the start of each round.
   * @param {object[]} spirits — array of spirit objects
   */
  logSpiritLoadout(spirits) {
    if (spirits.length === 0) {
      this._log('Spirits: (none)');
      return;
    }
    const lines = spirits.map(s => {
      let detail = s.name;
      if (s.state) {
        if (s.state.plainsCaptured !== undefined) detail += ` [plains: ${s.state.plainsCaptured}]`;
        if (s.state.seenAnimals) detail += ` [unique animals: ${s.state.seenAnimals.length}]`;
      }
      return detail;
    });
    this._log(`Spirits: ${lines.join(' | ')}`);
  }

  // ── Player actions ─────────────────────────────────────────────────────

  /**
   * @param {string} type — 'play', 'discard'
   * @param {object} details
   */
  logAction(type, details) {
    if (type === 'play') {
      const cards = details.cardIds || [details.cardId];
      this._log(`  PLAY: ${cards.map(id => id).join(', ')} → field month ${details.targetMonth ?? '?'}`);
    } else if (type === 'discard') {
      this._log(`  DISCARD: ${details.cardId}`);
    }
  }

  /**
   * @param {object} deckCard — the card flipped from the deck
   * @param {string} result — 'capture', 'strand', 'silk_capture', 'field_place', 'field_discard'
   * @param {object[]} capturedCards — cards captured as a result (if any)
   */
  logDeckFlip(deckCard, result, capturedCards) {
    let msg = `  FLIP: ${this._cardLabel(deckCard)} → ${result}`;
    if (capturedCards && capturedCards.length > 0) {
      msg += ` [captured: ${capturedCards.map(c => this._cardLabel(c)).join(', ')}]`;
    }
    this._log(msg);
  }

  /**
   * @param {object[]} cards — cards captured
   * @param {string} reason — 'match', 'auto_complete', 'four_card'
   */
  logCapture(cards, reason) {
    this._log(`  CAPTURE (${reason}): ${cards.map(c => this._cardLabel(c)).join(', ')}`);
  }

  // ── Yaku and style ─────────────────────────────────────────────────────

  /**
   * @param {object[]} yakuList — array of { name, bonus, count, threshold }
   * @param {object[]} newYaku — newly completed yaku this turn
   */
  logYakuState(yakuList, newYaku) {
    if (yakuList.length === 0) return;
    const yakuStr = yakuList.map(y => `${y.name} +${y.bonus.toFixed(1)} (${y.count}/${y.threshold})`).join(', ');
    this._log(`  YAKU: ${yakuStr}`);
    if (newYaku && newYaku.length > 0) {
      this._log(`  ► NEW YAKU: ${newYaku.map(y => y.name).join(', ')} → Bank/Push triggered`);
    }
  }

  /**
   * @param {object[]} combos — array of { name, bonus }
   */
  logStyleCombos(combos) {
    if (combos.length === 0) return;
    const str = combos.map(c => `${c.name} +${c.bonus.toFixed(1)}`).join(', ');
    this._log(`  STYLE: ${str}`);
  }

  // ── Bank/Push ──────────────────────────────────────────────────────────

  logBankPushDecision(decision, pushCount) {
    this._log(`  DECISION: ${decision.toUpperCase()} (push #${pushCount})`);
  }

  // ── Consumable usage ───────────────────────────────────────────────────

  /**
   * @param {string} consumableName
   * @param {string} action — description of what happened
   */
  logConsumableUse(consumableName, action) {
    this._log(`  CONSUMABLE: ${consumableName} — ${action}`);
  }

  // ── Round end ──────────────────────────────────────────────────────────

  /**
   * @param {object} scoring — full scoring breakdown
   * @param {number} threshold
   * @param {boolean} cleared
   * @param {object[]} capturedCards — full capture pile
   * @param {number} styleBase — Style Base after this round's combos
   * @param {object[]} triggeredCombos — style combos triggered this round
   * @param {string[]} enhancementEvents — any enhancement post-round events (breaks, etc.)
   */
  logRoundEnd(scoring, threshold, cleared, capturedCards, styleBase, triggeredCombos, enhancementEvents) {
    this._log('');
    this._log(`  ── Round ${this._currentRound} Scoring ──`);
    this._log(`  Captured: ${capturedCards.length} cards`);

    // Card type breakdown
    const types = { bright: 0, animal: 0, ribbon: 0, plain: 0, fire: 0 };
    for (const c of capturedCards) {
      if (c.enhancement?.element === 'fire') types.fire++;
      else types[c.type] = (types[c.type] ?? 0) + 1;
    }
    this._log(`  Types: ${types.bright}B ${types.animal}A ${types.ribbon}R ${types.plain}P` +
      (types.fire > 0 ? ` ${types.fire}F(wildcard)` : ''));

    // Scoring channels
    this._log(`  Base points: ${scoring.basePoints ?? '?'}`);
    if (scoring.pointBoostDetail) this._log(`  Point boosts: ${scoring.pointBoostDetail}`);
    this._log(`  Yaku mult: ${scoring.yakuMult?.toFixed(2) ?? '?'}`);
    if (scoring.additiveMult) this._log(`  Additive mult: +${scoring.additiveMult.toFixed(2)}`);
    if (scoring.multMult && scoring.multMult !== 1) this._log(`  Mult-mult: ×${scoring.multMult.toFixed(2)}`);
    this._log(`  Flow: ×${scoring.flow?.toFixed(2) ?? '?'} (Style Base: ${styleBase.toFixed(2)})`);
    this._log(`  FINAL SCORE: ${scoring.finalScore}`);
    this._log(`  Threshold: ${threshold} — ${cleared ? '✓ CLEARED' : '✗ FAILED'}`);

    // Style summary
    if (triggeredCombos && triggeredCombos.length > 0) {
      this._log(`  Style combos: ${triggeredCombos.map(c => c.name).join(', ')}`);
    }

    // Enhancement events
    if (enhancementEvents && enhancementEvents.length > 0) {
      for (const evt of enhancementEvents) {
        this._log(`  Enhancement: ${evt}`);
      }
    }
  }

  // ── Shop ───────────────────────────────────────────────────────────────

  logShopEnter(kiBalance, isGrove) {
    this._log('');
    this._log(`  ── ${isGrove ? 'Sacred Grove' : 'Wayside Shrine'} (Ki: ${kiBalance}) ──`);
  }

  logShopPurchase(category, itemName, cost, details) {
    let msg = `  BUY: ${itemName} (${cost} ki)`;
    if (details) msg += ` — ${details}`;
    this._log(msg);
  }

  logShopFusion(spiritA, spiritB, result) {
    this._log(`  FUSE: ${spiritA} + ${spiritB} → ${result}`);
  }

  logShopExit(kiBalance) {
    this._log(`  Exit shop (Ki: ${kiBalance})`);
  }

  // ── Run summary ────────────────────────────────────────────────────────

  /**
   * Generate a summary block at the end of the run.
   * @param {object} runState — snapshot of RunManager state
   */
  logRunSummary(runState) {
    this._separator('RUN SUMMARY');
    this._log(`Rounds completed: ${runState.round}`);
    this._log(`Final ki: ${runState.ki}`);

    // Spirits
    if (runState.spirits && runState.spirits.length > 0) {
      this._log(`Spirits: ${runState.spirits.map(s => {
        let detail = s.name;
        if (s.state?.plainsCaptured !== undefined) detail += ` [plains: ${s.state.plainsCaptured}]`;
        if (s.state?.seenAnimals) detail += ` [animals: ${s.state.seenAnimals.length}/9]`;
        return detail;
      }).join(', ')}`);
    }

    // Yaku upgrades
    if (runState.yakuUpgrades) {
      const ups = runState.yakuUpgrades;
      const upgradeStr = Object.entries(ups)
        .filter(([, v]) => v > 0)
        .map(([k, v]) => `${k}: ${v}×(+0.2)`)
        .join(', ');
      if (upgradeStr) this._log(`Yaku upgrades: ${upgradeStr}`);
    }

    // Deck state
    if (runState.deckSize !== undefined) {
      this._log(`Deck size: ${runState.deckSize}/48`);
    }

    // Enhanced cards
    if (runState.enhancedCards && runState.enhancedCards.length > 0) {
      this._log(`Enhanced cards:`);
      for (const c of runState.enhancedCards) {
        this._log(`  ${c.id}: ${c.enhancement.tier} ${c.enhancement.element}` +
          (c.enhancement.depLevel !== undefined ? ` (dep: ${c.enhancement.depLevel})` : ''));
      }
    }

    // Promoted cards
    if (runState.promotedCards && runState.promotedCards.length > 0) {
      this._log(`Promoted cards:`);
      for (const c of runState.promotedCards) {
        this._log(`  ${c.id} (${c.type})`);
      }
    }
  }

  // ── Helpers ─────────────────────────────────────────────────────────────

  _cardLabel(card) {
    let label = card.name ?? card.id;
    if (card.enhancement) {
      const enh = card.enhancement;
      const names = {
        water: { base: 'Snow', upgraded: 'Ice' },
        wood:  { base: 'Leaf', upgraded: 'Silk' },
        fire:  { base: 'Ember', upgraded: 'Charcoal' },
        earth: { base: 'Clay', upgraded: 'Pottery' },
        metal: { base: 'Iron', upgraded: 'Meteorite' },
      };
      const enhName = names[enh.element]?.[enh.tier] ?? enh.element;
      label += `[${enhName}`;
      if (enh.element === 'water') {
        const SNOW = [2.0, 1.5, 1.0, 0.75, 0.5, 0.25];
        const ICE  = [4.0, 3.0, 2.0, 1.5, 1.0, 0.75, 0.5, 0.25];
        const arr = enh.tier === 'upgraded' ? ICE : SNOW;
        const lvl = Math.min(enh.depLevel ?? 0, arr.length - 1);
        label += ` ×${arr[lvl]}`;
      }
      label += ']';
    }
    if (card.promotionProgress) {
      label += `{promo:${card.promotionProgress}}`;
    }
    return label;
  }

  // ── Output ──────────────────────────────────────────────────────────────

  /**
   * Get the full transcript as a string.
   */
  getTranscript() {
    return this._entries.join('\n');
  }

  /**
   * Copy transcript to clipboard (browser only).
   */
  async copyToClipboard() {
    const text = this.getTranscript();
    try {
      await navigator.clipboard.writeText(text);
      console.log('[GameplayLogger] Transcript copied to clipboard.');
      return true;
    } catch (e) {
      console.warn('[GameplayLogger] Clipboard copy failed:', e);
      return false;
    }
  }

  /**
   * Log transcript to browser console.
   */
  printToConsole() {
    console.log(this.getTranscript());
  }
}

const logger = new GameplayLogger();
export default logger;
